Repository pipelines-lol/pipelines, pull requests merged in 2024-04, with the labels that each got.

#133 REACTIVE Token Refreshing + Context Restructure
  client/src/context/SessionContext.js
  client/src/hooks/useSessionContext.js
  client/src/index.js
  client/src/util/fetchUtils.js
  client/src/util/tokenUtils.js
Labels: bug, enhancement

#135 Fetch Function Error Fix
  client/src/util/fetchUtils.js
Labels: bug

#137 Backend Logs
  server/controllers/authController.js
  server/controllers/companyController.js
  server/controllers/emailController.js
  server/controllers/pipelineController.js
  server/controllers/profileController.js
  server/models/userModel.js
Labels: enhancement

#138 Token Generation Fix + Robust Fetch
  client/src/util/fetchUtils.js
  server/middleware/token.js
Labels: bug, enhancement

#139 Linkedin Token API Security
  client/src/components/Navbar.js
  client/src/util/fetchUtils.js
  client/src/util/mongoUtils.js
  client/src/util/tokenUtils.js
  server/controllers/authController.js
  server/index.js
  server/middleware/token.js
  server/middleware/user.js
  server/routes/auth.js
  server/routes/pipelines.js
  server/routes/profiles.js
  server/routes/token.js
Labels: bug, enhancement

#142 [ 🚑 HOTFIX ] Login Fix
  server/controllers/authController.js
Labels: bug

#144 Admin Page! 🎉
  client/src/App.js
  client/src/context/AdminContext.js
  client/src/context/EarlyAccessContext.js
  client/src/hooks/useAdminContext.js
  client/src/index.js
  client/src/pages/(admin)/Admin.js
  client/src/pages/(admin)/AdminDashboard.js
  client/src/pages/(admin)/AdminLogin.js
  client/src/util/tokenUtils.js
  server/controllers/adminController.js
  server/controllers/authController.js
  server/controllers/companyController.js
  server/index.js
  server/middleware/admin.js
  server/middleware/token.js
  server/models/adminModel.js
  server/models/companyModel.js
  server/routes/admin.js
  server/routes/companies.js
  server/routes/token.js
Labels: enhancement

#146 Login Security + Bug Squashing
  client/src/components/Navbar.js
  client/src/context/AuthContext.js
  client/src/pages/EditProfile.js
  client/src/util/fetchUtils.js
  server/controllers/authController.js
  server/controllers/companyController.js
  server/index.js
  server/middleware/profile.js
  server/middleware/user.js
  server/routes/auth.js
Labels: bug, enhancement

#147 Username Validation Fix
  client/src/pages/Profile.js
Labels: bug

#148 [ 🚀 HOTFIX ] Profile Creation Fix
  client/src/App.js
  client/src/components/Navbar.js
  client/src/components/nav/Mobile.js
  client/src/components/nav/NonMobile.js
  client/src/pages/EditProfile.js
  server/middleware/profile.js
Labels: bug

#150 PFP + Linkedin Bug Fix
  client/src/components/Navbar.js
  client/src/components/landing/Offerings.js
  client/src/util/generalUtils.js
Labels: bug

#151 Let's go bug squashing
  client/src/pages/EditProfile.js
  server/controllers/companyController.js
Labels: bug

#152 Code cleanup
  client/src/components/ExperienceForm.js
  client/src/hooks/useValidateExperience.js
  client/src/pages/EditProfile.js
  client/src/util/generalUtils.js
  server/controllers/companyController.js
  server/package.json
  server/routes/companies.js
  server/utils/generalUtils.js
Labels: enhancement

#155 Discord Community Link README Addition
  README.md
Labels: documentation, enhancement

#163 School Front-end Implementation!
  client/src/App.js
  client/src/components/PipelineCard.js
  client/src/pages/Company.js
  client/src/pages/Profile.js
  client/src/pages/School.js
  server/controllers/companyController.js
  server/models/schoolModel.js
  server/routes/companies.js
Labels: bug, enhancement

#164 School Profile Display Fix!
  client/src/pages/Profile.js
Labels: bug
